config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :issues, only: :index
  resources :repositories
  root to: 'issues#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/scopable.rb
module Scopable
  extend ActiveSupport::Concern

  included do
    scope :ordered, -> { order(created_at: :desc) }
  end
end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id            :integer          not null, primary key
#  name          :string
#  description   :string
#  url           :string
#  repository_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  number        :integer          default(0), not null
#  closed        :boolean          default(FALSE)
#

class Issue < ApplicationRecord
  include Scopable
  belongs_to :repository

  validates :number, uniqueness: { scope: :repository_id }

  enum complexity: [:beginner, :intermediate, :proficient]

  scope :opened, -> { where(closed: false) }
  scope :closed, -> { where(closed: true) }

  def update_from_github
    issue =
      Octokit.issue("#{repository.user.username}/#{repository.name}", number)

    update(
      name: issue[:title],
      description: issue[:body],
      closed: Issue.closed?(issue[:state]),
    )
  end

  def self.closed?(state)
    state == 'close' ? true : false
  end
end

app/models/repository.rb
# == Schema Information
#
# Table name: repositories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  url         :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Repository < ApplicationRecord
  include Scopable
  belongs_to :user
  has_many :issues, dependent: :destroy

  validates :name, uniqueness: { scope: :user_id }

  delegate :username, to: :user, prefix: :owner
  delegate :email, to: :user, prefix: :owner

  def search_on_github(username, repo)
    Octokit.repo("#{username}/#{repo}") rescue nil
  end

  def get_issues
    remote_issues = Octokit.issues("#{user.username}/#{name}")

    remote_issues.select { |issue| Labels.list(issue).include?('RubyNoob') }
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string
#  provider               :string
#  uid                    :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :omniauthable, omniauth_providers: [:github]

  has_many :repositories

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.nickname
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.includes(:repository)
                   .opened
                   .ordered
                   .paginate(page: params[:page])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  def index
    @repositories = Repository.ordered.paginate(page: params[:page])
  end

  def show
  end

  def new
    @repository = Repository.new
  end

  def edit
  end

  def create
    @repository = current_user.repositories.build(repository_params)

    repo = @repository.search_on_github(
             current_user.username, repository_params[:name]
           )

    if repo
      @repository = current_user.repositories.build(
                      name: repo[:name],
                      description: repo[:description],
                      url: repo[:html_url]
                    )
      @repository.save!

      redirect_to @repository, notice: 'Repository was successfully created.'
    else
      redirect_to :back, alert: 'Repo not found!'
    end
  end

  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_repository
    @repository = Repository.find(params[:id])
  end

  def repository_params
    params.require(:repository).permit(:name, :description, :url)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def github
      @user = current_user || User.from_omniauth(oauth_data)

      if current_user
        current_user.update_omniauth_data oauth_data
        redirect_to :back
      elsif @user.persisted?
        sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
      else
        session['devise.github_data'] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end

    private

    def oauth_data
      request.env['omniauth.auth']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def avatar_url(email, size)
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/issues/index.html.slim
table.table.table-hover
  - @issues.each do |issue|
    tr
      td
        = link_to issue.url.html_safe do
          => image_tag(avatar_url(issue.repository.owner_email, 20))
          => "[#{issue.repository.name}]"
          = "#{issue.name} ##{issue.number}"
      td.text-right
        = "#{time_ago_in_words(issue.created_at)} ago"

.text-center = will_paginate @issues

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubynoob</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render 'shared/navbar' %>
      <%= render partial: 'shared/flash_messages', flash: flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.slim
table.table.table-hover
  tr
    td
      img> src="http://lorempixel.com/17/17/" alt=""
      | [Owner:Repo] Test github issue #1
    td
      span.label.label-danger.pull-right Proficient

app/views/repositories/_form.html.slim
.col-md-4
  = form_for @repository do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'

    = f.submit 'Add repo', class: 'btn btn-primary'

app/views/repositories/edit.html.slim
h1 Editing repository

== render 'form'

= link_to 'Show', @repository
'|
= link_to 'Back', repositories_path

app/views/repositories/index.html.slim
table.table.table-hover
  - @repositories.each do |repo|
    tr
      td
        = link_to repo.url.html_safe do
          => image_tag(avatar_url(repo.user.email, 20))
          => "[#{repo.owner_username}]"
          = repo.name

.text-center = will_paginate @issues

app/views/repositories/new.html.slim
h1 New repository

= render 'form'

app/views/repositories/show.html.slim
p#notice = notice

p
  strong Name:
  = @repository.name
p
  strong Description:
  = @repository.description
p
  strong Url:
  = @repository.url
p
  strong User:
  = @repository.user_id

= link_to 'Edit', edit_repository_path(@repository)
'|
= link_to 'Back', repositories_path

app/views/shared/_flash_messages.slim
.alerts
  - flash.each do |type, message|
    .alert.fade.in class=alert_class_for(type)
      button.close data-dismiss='alert' ×
      = message

app/views/shared/_navbar.slim
nav.navbar.navbar-default
  .navbar-header
    button { class = 'navbar-toggle collapsed'
             type = 'button'
             data-toggle = 'collapse'
             data-target = '#navbar-collapse'
             aria-expanded = 'false'
           }
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to 'Brand', root_path, class: 'navbar-brand'
  .collapse.navbar-collapse id='navbar-collapse'
    ul.nav.navbar-nav
      li
        = link_to 'Repositories', repositories_path
    ul.nav.navbar-nav.navbar-right
      - if signed_in?
        li.dropdown
          a.dropdown-toggle href='#' data-toggle='dropdown'
            i.glyphicon.glyphicon-th-large
            span.caret
          ul.dropdown-menu role='menu'
            li = link_to current_user.username, '#'
            li
              = link_to new_repository_path do
                i.glyphicon.glyphicon-plus>
                | Add new repo
            li
              = link_to destroy_user_session_path, data: { method: :delete } do
                i.glyphicon.glyphicon-log-out>
                | Sign out
      - else
        li.dropdown
          a.dropdown-toggle href='#' data-toggle='dropdown'
            i.glyphicon.glyphicon-lock
            span.caret
          ul.dropdown-menu role='menu'
            li = link_to 'Sign in via Github', user_github_omniauth_authorize_path